name: PHP Build (zonder Composer)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 📦 Checkout repo
      uses: actions/checkout@v4

    - name: ✅ Test stap zonder Composer
      run: echo "Geen Composer nodig – workflow uitgevoerd!"
